worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Evitar exponer versión de Nginx
    server_tokens off;

    # Rate Limiting (Protección contra DDoS / Fuerza Bruta)
    # Define una zona de memoria (10MB) permitiendo en promedio 10 peticiones por segundo por IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    server {
        listen 80;

        # Seguridad de subida: Limitar tamaño a 20MB
        client_max_body_size 20M;

        # Mitigación Slowloris: Reducir los timeouts drásticamente
        client_body_timeout 10s;
        client_header_timeout 10s;
        keepalive_timeout 5s;
        send_timeout 10s;

        # Security Headers (Defensa en profundidad)
        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";

        location / {
            # Aplicar Rate Limiting (Permitir ráfagas de hasta 20 peticiones sin delay inmediato)
            limit_req zone=api_limit burst=20 nodelay;

            # Proxy Pass hacia Axum (Rust Backend)
            proxy_pass http://api_rest:8080;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
